steps:
  - name: node
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        cd ./src/api
        npm install
  - name: node
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        cd ./src/frontend
        npm install
        npm run build
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        cd ./src/frontend
        gcloud app deploy
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        cd ./src/api
        gcloud app deploy
    # args: ["app", "deploy"]
timeout: "1600s"
